# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odds < Formula
  desc "CLI for The Odds API v4"
  homepage "https://github.com/mgm702/odds-api"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_darwin_amd64.tar.gz"
      sha256 "4631f06d433db1fdae7f5b9040c565bc9dd92430181252db8b28de38fff22d92"

      define_method(:install) do
        bin.install "odds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_darwin_arm64.tar.gz"
      sha256 "cf8145fc43d3c5c5740bde0eee1ffbe176825360ec799cbf7a4c88845c1da1ed"

      define_method(:install) do
        bin.install "odds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_linux_amd64.tar.gz"
      sha256 "ddd3da33fd4ee1f070ac6e9d8ff4281f5468247e1548df82ae6610ef7853ec16"
      define_method(:install) do
        bin.install "odds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_linux_arm64.tar.gz"
      sha256 "7dbef48885535024ce232def638e082ad0a7bb39fdd5eda7d7b263c53a76f527"
      define_method(:install) do
        bin.install "odds"
      end
    end
  end

  test do
    system "#{bin}/odds", "--version"
  end
end
