# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odds < Formula
  desc "CLI for The Odds API v4"
  homepage "https://github.com/mgm702/odds-api"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgm702/odds-api/releases/download/v0.2.0/odds_0.2.0_darwin_amd64.tar.gz"
      sha256 "a7d0db57e05143614c9458d4a2e86b057a132bc0e7736b5a83a638eb62639076"

      define_method(:install) do
        bin.install "odds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgm702/odds-api/releases/download/v0.2.0/odds_0.2.0_darwin_arm64.tar.gz"
      sha256 "6abcdc3f4da18c90c99c5318e993180f86be84d3c1b95d3cba10a2d5827beda4"

      define_method(:install) do
        bin.install "odds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/odds-api/releases/download/v0.2.0/odds_0.2.0_linux_amd64.tar.gz"
      sha256 "2c8335db4bfb7c0ba45d17441d76cebcb2e5cdcd904415dca44ec50ce8cb3db6"
      define_method(:install) do
        bin.install "odds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/odds-api/releases/download/v0.2.0/odds_0.2.0_linux_arm64.tar.gz"
      sha256 "1726607c8649d19e6b6e7c402f2641a68a1a25e76702f37e1b2df6ce199a60b1"
      define_method(:install) do
        bin.install "odds"
      end
    end
  end

  test do
    system "#{bin}/odds", "--version"
  end
end
