# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odds < Formula
  desc "CLI for The Odds API v4"
  homepage "https://github.com/mgm702/odds-api"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_darwin_amd64.tar.gz"
      sha256 "090c8864cf239ed94b3474f476ddb8360c9125072dfaddfbb1195a290ff22050"

      define_method(:install) do
        bin.install "odds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_darwin_arm64.tar.gz"
      sha256 "bade6d17f897607056f9b3fc4eab181821fba515ab2b20f465c4a30af229e4ec"

      define_method(:install) do
        bin.install "odds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_linux_amd64.tar.gz"
      sha256 "a2249ab9f537103bcec9cbf4b7b9daf6bbf77a3f2367511fa341db530543a7d8"
      define_method(:install) do
        bin.install "odds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/odds-api/releases/download/v0.1.0/odds_0.1.0_linux_arm64.tar.gz"
      sha256 "002b218cf50e9539895a3e9e0a9af54bb027a4d9be78a4dafa103f558e5ab587"
      define_method(:install) do
        bin.install "odds"
      end
    end
  end

  test do
    system "#{bin}/odds", "--version"
  end
end
